### ISSUE TITLE
How specific are we going to get

### ISSUE THREAD

**Issue by DTSCode** [TheRabbitologist/DevGarden#2]
Is there any reason why I can't use gcc or will I have to build clang to satisfy you llvm freaks :D?

**Comment by TheRabbitologist** [comment]
I don't see why we couldn't use gcc for building. It's C++11 support is decent, finally. Is there anything in the project file that stops you from building with gcc?

**Comment by DTSCode** [comment]
No. Nothing that I could see. I was just making sure that anything I built
later on would be a result of Comiller's

**Comment by TheRabbitologist** [comment]
Should we recommend compilers to use and limit ourselves to the smallest intersect of the sets of features they each offer?

**Comment by TheRabbitologist** [comment]
Just had a chat about this on the IRC. The long answer's yes.
