### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ResidentBiscuit** [TheRabbitologist/DevGarden#6]
I think it would be wise to adopt a strong documentation strategy from the beginning. It's always easier to start with it than to go back and document everything. I'm a big fan of Doxygen, as I'm sure many people are.

**Comment by TheRabbitologist** [comment]
I'm inclined to agree, including about the Doxygen. One detail: where would we put the generated documentation pages? gh-pages, or somewhere else?

**Comment by ResidentBiscuit** [comment]
Gh-pages would probably be best, at least for now.

**Comment by TheRabbitologist** [comment]
I've started documenting our code on my branch. Mostly the purpose of each class, but also some signals and more obscure functions.
